[env:atmega328pb_baremetal]
platform = atmelavr
board = ATmega328PB_custom
board_build.mcu = atmega328pb
board_build.f_cpu = 16000000L
upload_protocol = custom
upload_port = /dev/cu.usbmodem112401
upload_speed = 57600
build_flags = -Os -Wall -std=gnu99

upload_command = /Users/topsecret/Library/Arduino15/packages/MiniCore/tools/avrdude/8.0-arduino.1/bin/avrdude -C /Users/topsecret/Library/Arduino15/packages/MiniCore/tools/avrdude/8.0-arduino.1/etc/avrdude.conf -v -p atmega328pb -c urclock -P /dev/cu.usbmodem112401 -b 57600 -D -U flash:w:$BUILD_DIR/firmware.hex:i
